// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBufl1SE70ZYmkKmEJRudBFiTcaceBAaI0',
    appId: '1:755767819731:web:fb97d1cfd7861c04a70326',
    messagingSenderId: '755767819731',
    projectId: 'rick-and-morty-86a26',
    authDomain: 'rick-and-morty-86a26.firebaseapp.com',
    storageBucket: 'rick-and-morty-86a26.firebasestorage.app',
    measurementId: 'G-21TDJNE6N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlF36h-N0gLCxbXHGxPjF2tVaXjnPT3DI',
    appId: '1:755767819731:android:a3538d5f7f98281ca70326',
    messagingSenderId: '755767819731',
    projectId: 'rick-and-morty-86a26',
    storageBucket: 'rick-and-morty-86a26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNi9gkze2f3CTpWhBuL94lZPsdb8x-SU4',
    appId: '1:755767819731:ios:029c5f5f2b6189eba70326',
    messagingSenderId: '755767819731',
    projectId: 'rick-and-morty-86a26',
    storageBucket: 'rick-and-morty-86a26.firebasestorage.app',
    iosBundleId: 'com.example.rickandmortyapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNi9gkze2f3CTpWhBuL94lZPsdb8x-SU4',
    appId: '1:755767819731:ios:029c5f5f2b6189eba70326',
    messagingSenderId: '755767819731',
    projectId: 'rick-and-morty-86a26',
    storageBucket: 'rick-and-morty-86a26.firebasestorage.app',
    iosBundleId: 'com.example.rickandmortyapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBufl1SE70ZYmkKmEJRudBFiTcaceBAaI0',
    appId: '1:755767819731:web:6fe1ec9c0adf1a4aa70326',
    messagingSenderId: '755767819731',
    projectId: 'rick-and-morty-86a26',
    authDomain: 'rick-and-morty-86a26.firebaseapp.com',
    storageBucket: 'rick-and-morty-86a26.firebasestorage.app',
    measurementId: 'G-2MF4JJ4NYN',
  );
}
